name: Build and Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        omp: [OFF, ON]
        mpi: [OFF, ON]
    name: "(OpenMP, MPI) ="
    runs-on: ubuntu-20.04
    env:
      BUILD_DIR: build_${{ matrix.omp }}_${{ matrix.mpi }}
      OMP_NUM_THREADS: 4
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libopenblas-dev liblapack-dev libhdf5-dev libhdf5-openmpi-dev libscalapack-openmpi-dev python3-pip -o Acquire::Retries=3 --fix-missing
          pip3 install numpy
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Configure
        run: |
          mkdir ${BUILD_DIR}
          cd ${BUILD_DIR}
          cmake .. -DOMP_AVAIL=${{ matrix.omp }} -DKokkos_ENABLE_OPENMP=${{ matrix.omp }} -DMPI_AVAIL=${{ matrix.mpi }} -DHDF5_AVAIL=ON
      - name: Build
        run: |
          cd ${BUILD_DIR}
          make -j4
          make -j4 runTests
      - name: RunTests
        run : |
          cd ${BUILD_DIR}
          ./runTests
      - name: Download test data
        run: |
          wget github.com/mir-group/phoebe-data/archive/master.zip
          unzip -j master.zip "phoebe-data-master/example/Silicon-ph/qe-phonons/*" -d "example/Silicon-ph/qe-phonons"
          unzip -j master.zip "phoebe-data-master/example/Silicon-ph/qe-ph-anharmonic/*" -d "example/Silicon-ph/thirdorder.py-anharmonic"
          unzip -j master.zip "phoebe-data-master/example/Silicon-el/qe-elph/*" -d "example/Silicon-el/qe-elph"
          unzip 'example/Silicon-el/qe-elph/silicon.phoebe.*.dat.zip' -d example/Silicon-el/qe-elph/
          cp example/Silicon-el/qe-elph/* example/Silicon-epa/qe-elph
          mkdir example/Silicon-epa/qe-elph/out
          unzip -j master.zip "phoebe-data-master/example/Silicon-epa/qe-elph/out/*" -d "example/Silicon-epa/qe-elph/out"
      - name: Run epa example without MPI
        working-directory: example/Silicon-epa
        run: |
          ../../${BUILD_DIR}/phoebe -in qeToPhoebeEPA.in
          ../../${BUILD_DIR}/phoebe -in epaTransport.in
          ../../${BUILD_DIR}/phoebe -in electronFourierBands.in
          ../../${BUILD_DIR}/phoebe -in electronFourierDos.in
          python3 reference/run_check.py
      - name: Run epa example with MPI
        working-directory: example/Silicon-epa
        if: matrix.mpi == 'ON'
        run: |
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in epaTransport.in
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in electronFourierBands.in
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in electronFourierDos.in
          python3 reference/run_check.py
      - name: Run ph example without MPI
        working-directory: example/Silicon-ph
        run: |
          ../../${BUILD_DIR}/phoebe -in phononTransport.in
          ../../${BUILD_DIR}/phoebe -in phononBands.in
          ../../${BUILD_DIR}/phoebe -in phononDos.in
          ../../${BUILD_DIR}/phoebe -in phononLifetimes.in
          python3 reference/run_check.py
      - name: Run ph example with MPI
        working-directory: example/Silicon-ph
        if: matrix.mpi == 'ON'
        run: |
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in phononTransport.in
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in phononBands.in
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in phononDos.in
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in phononLifetimes.in
          python3 reference/run_check.py
      - name: Run el example without MPI
        working-directory: example/Silicon-el
        run: |
          ../../${BUILD_DIR}/phoebe -in qeToPhoebeWannier.in
          ../../${BUILD_DIR}/phoebe -in electronWannierTransport.in
          ../../${BUILD_DIR}/phoebe -in electronWannierBands.in
          ../../${BUILD_DIR}/phoebe -in electronWannierDos.in
          ../../${BUILD_DIR}/phoebe -in electronLifetimes.in
          python3 reference/run_check.py
      - name: Run el example with MPI
        working-directory: example/Silicon-el
        if: matrix.mpi == 'ON'
        run: |
          # Note: don't run this as it runs out-of-memory on the VM
          #mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in qeToPhoebeWannier.in
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in electronWannierTransport.in
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in electronWannierBands.in
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in electronWannierDos.in
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -in electronLifetimes.in
          python3 reference/run_check.py
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -ps 2 -in electronWannierTransport.in
          mpirun -np 4 --oversubscribe ../../${BUILD_DIR}/phoebe -ps 2 -in electronLifetimes.in
          python3 reference/run_check.py

